### ISSUE TITLE
Allow different port numbers other than standard 8080, 2023

### ISSUE THREAD

**Issue by Daksol** [Jamesits/docker-ripe-atlas#39]
Hi.
The sw probe repo has implemented a change to allow different port numbers to be used - instead of the default ones of 8080 and 2023.

See https://github.com/RIPE-NCC/ripe-atlas-software-probe/pull/92

Could you advise what changes required to the docker-compose yaml file in order to use other port numbers?

Thanks.

**Comment by Jamesits** [comment]
If you are running the container in its own network namespace, there is no need to change the ports. They don't collide with anything else.

If you are using `--network=host`, then just set the environment variables `HTTP_POST_PORT` and `TELNETD_PORT` on the container.

Example:
```yaml
services:
  ripe-atlas:
# ...
    environment:
# ...
      HTTP_POST_PORT: "8888"
```
