### ISSUE TITLE
Seeing '/var/atlasdata is not mounted' in the log

### ISSUE THREAD

**Issue by GoWithitRoger** [Jamesits/docker-ripe-atlas#9]
I've got this running through Portainer in Home Assistant (formerly Hassio) on a RPi3. But I keep running into the log error '/var/atlasdata is not mounted', appearing after startup of the probe looks to go correctly.

Log starts out:
```
Option RXTXRPT=yes
/usr/local/bin/atlas: 175: /usr/local/atlas/bin/arch/debian-sw-probe/debian-sw-probe-ATLAS.sh: cannot open /var/atlas-probe/etc/probe_key.pub: No such file
Generating public/private rsa key pair.
Your identification has been saved in /var/atlas-probe/etc/probe_key.
Your public key has been saved in /var/atlas-probe/etc/probe_key.pub.
The key fingerprint is:
KEY HERE

The key's randomart image is:
+---[RSA 2048]----+...
```

I've tried adding a volume mapping for var/atlasdata" but it results in the same error, but at an earlier point, even before the log shows the probe started up.

The compose file I'm using:

```
version: '2.4'
services:
    ripe-atlas:
      restart: unless-stopped
      volumes:
         - '/var/atlas-probe/etc:/var/atlas-probe/etc'
         - '/var/atlas-probe/status:/var/atlas-probe/status'
      environment:
         - RXTXRPT=yes
      container_name: ripe-atlas
      image: 'jamesits/ripe-atlas:latest-armv7l'
```

**Comment by Jamesits** [comment]
Atlas hardcoded a lot checks for their own probes so we have to replicate exactly the config they had. The method is already documented: https://github.com/Jamesits/docker-ripe-atlas#running and you just need to adopt it.

Add the following section to your docker-compose file:

```yaml
volumes:
      - type: tmpfs
        target: /var/atlasdata
        size: 67108864
```

**Comment by GoWithitRoger** [comment]
Interestingly, I did start with that additional "volumes:..." part, from the command you have in the read-me. But it looks like when I converted to a Compose file (using https://www.composerize.com) it takes it out.

Adding it directly to the compose config in differing ways gets a couple of errors, but I'm guessing it could be do 'temps' and using version 2.4 and not 3 ([Docker documentation](https://docs.docker.com/compose/compose-file/#tmpfs) suggests this). But of course me not structuring the compose file correctly is a big possibility.

This returns the error: unmarshal errors: line 14: cannot unmarshal !!seq into map[string]interface{}
```
--- 
version: "2.4"
services: 
  ripe-atlas:
      restart: unless-stopped
      volumes:
        - "/var/atlas-probe/etc:/var/atlas-probe/etc"
        - "/var/atlas-probe/status:/var/atlas-probe/status"
      environment: 
        - RXTXRPT=yes
      container_name: ripe-atlas
      image: "jamesits/ripe-atlas:latest-armv7l"
volumes:
  - type: tmpfs
    target: "/var/atlasdata"
    size: 67108864

```

And this way (which probably shows how little I know of docker and compose) returns: service 'ripe-atlas' configuration key '2' contains and invalid type, it should be a string.
```
--- 
version: "2.4"
services: 
  ripe-atlas:
      restart: unless-stopped
      volumes:
        - "/var/atlas-probe/etc:/var/atlas-probe/etc"
        - "/var/atlas-probe/status:/var/atlas-probe/status"
        - type: tmpfs
          target: "/var/atlasdata"
          size: 67108864
      environment: 
        - RXTXRPT=yes
      container_name: ripe-atlas
      image: "jamesits/ripe-atlas:latest-armv7l"
```

**Comment by Jamesits** [comment]
Try this config (I wrote it blindly as I don't have a debug env right now; tell me if it doesn't work):

```yaml
version: "2.4"
services: 
  ripe-atlas:
      container_name: ripe-atlas
      image: "jamesits/ripe-atlas:latest-armv7l"
      restart: unless-stopped
      volumes:
        - "/var/atlas-probe/etc:/var/atlas-probe/etc"
        - "/var/atlas-probe/status:/var/atlas-probe/status"
      tmpfs:
        - "/var/atlasdata"
      environment: 
        - RXTXRPT=yes
```

> using version 2.4 and not 3.6 (Docker documentation suggests this)

docker-compose v2 and docker-compose v3 are *completely different* things under one misleading name. Anything you find in the documentation for docker-compose v3 is only valid for v3 (3.0-3.6 or higher revisions), but not v2.x, vice versa. Don't look at the wrong documentation. If you are not using Swarm Mode, I recommend that you stick with the latest revision of docker-compose v2. 

[`tmpfs` support for docker-compose v2](https://docs.docker.com/compose/compose-file/compose-file-v2/#tmpfs) has always been here since 2.0, but for v3 it is only added after 3.6.
